### ISSUE TITLE
Error: Derived type ‘type_model’ at (1) is being used before it is defined

### ISSUE THREAD

**Issue by dharmaraharja96** [fabm-model/fabm#14]
Hi

When I compiled FVCOM-FABM-ERSEM, I find an error like this:

mod_fabm_data.f90:23:19:

   TYPE (type_model), PUBLIC :: model
                   1
Error: Derived type ‘type_model’ at (1) is being used before it is defined
makefile:42: recipe for target 'mod_fabm_data.o' failed
make: *** [mod_fabm_data.o] Error 1

How I can solve this error from mod_fabm_data.f:

```
MODULE MOD_FABM_DATA
# if defined(FABM)

  USE fabm
  USE MOD_PREC
  
  IMPLICIT NONE

  PRIVATE 

  TYPE (type_model), PUBLIC :: model

  REAL(SP), ALLOCATABLE, PUBLIC, TARGET ::  FABM_ALL(:,:,:)    ! 3D FABM state variables
  REAL(SP), ALLOCATABLE, PUBLIC, TARGET ::  FABM_ALL_BT(:,:)   ! 2D FABM bottom-attached state variables
  REAL(SP), ALLOCATABLE, PUBLIC, TARGET ::  FABM_ALL_SF(:,:)   ! 2D FABM surface-attached state variables
  REAL(DP), ALLOCATABLE, PUBLIC, TARGET ::  FABM_TOTALS(:)     ! Domain integrals of conserved quantities
  CHARACTER(LEN=80), PUBLIC :: STARTUP_FABM_TYPE  ! Initialization method ("constant" for spatially homogeneous, "set values" for read from restart)
  LOGICAL, PUBLIC :: FABM_DIAG_OUT
  LOGICAL, PUBLIC, ALLOCATABLE :: DISABLE_TRANSPORT(:)
  INTEGER, PUBLIC :: IFABMadv ! value of number of variables to advect
  INTEGER, PUBLIC, ALLOCATABLE :: IFABMadv_idx(:)
  INTEGER, PUBLIC :: IFABMnest ! value of number of variables in nesting file
  INTEGER, PUBLIC, ALLOCATABLE :: IFABMnest_idx(:) ! map of nesting variables to advectable variables
#   if defined (OFFLINE_FABM)
  CHARACTER(LEN=80), PUBLIC :: OFFLINE_FABM_FILE  ! File with physics forcing for offline biogeochemistry simulation
#   endif
# endif

END MODULE
```

For this case, I'm using FABM-ERSEM_v43 from UK-FVCOM.
Anyone can help me how to solve this problem? Thanks.

**Comment by jornbr** [comment]
I see that you've already closed this issue, so perhaps it has been solved? In any case, this is typically a question for the FVCOM mailing list. My guess is, however, that you are using an FVCOM version that was written to be coupled to an older FABM version (below v1.0), but you are trying to combine it with a more recent FABM version. You may have to change your FVCOM codebase (e.g., the branch you're using) to get support for FABM >= 1.0.

**Comment by dharmaraharja96** [comment]
Hi @jornbr 

Thank you for your response; yes, I have solved it. I was wrong in reading the version, but I have adjusted it and have modified a little bit of fvcom code in the installation process.
