### ISSUE TITLE
how to use FABM+GOTM

### ISSUE THREAD

**Issue by alexfight** [fabm-model/fabm#2]
HI guys:
     I am trying to FABM+GOTM, and I followed the instruction to install FABM, After the command "make install", the instruction ends. I now gave both FABM files and GOTM files in $HOME> Both FABM and GOTM files have src folder, where should I compile, what is the command for compiling and after compiling where should I run it. Is it same with GOTM? Go to testcase folder and link it to compiler "gotm", then run it with ./gotm? I have tried many times, but totally no idea how to make it work. Please give me the basic introduction of how to using FABM+GOTM. 

Sincerely
Ale

**Comment by jornbr** [comment]
For compilation instruction, please look [here](../wiki/GOTM)

After you compile GOTM with FABM support, you can add your biogeochemical configuration file (`fabm.yaml`) to your GOTM setup as described [here](../wiki/Setting-up-a-simulation).

Jorn
