### ISSUE TITLE
Incorrect multiplier in 0D driver call to calculate the density

### ISSUE THREAD

**Issue by jimc101** [fabm-model/fabm#21]
I believe the multiplier should be .5_rk and not 5._rk as it currently is.

https://github.com/fabm-model/fabm/blob/a0d56f0ce590dc35168e75a2ac1ca7bffd911fb6/src/drivers/0d/fabm0d.F90#L619

**Comment by jornbr** [comment]
Thanks! That seems correct (rho_feistel takes pressure in dbar, which is approximately equivalent to dept in m). Now fixed.
