### ISSUE TITLE
Is it possible to add multiple spm particles in spm mode?

### ISSUE THREAD

**Issue by RuoLinCunJi** [fabm-model/fabm#22]
Eg spm1(diameter 60),spm2(diameter 100);
Cheers

**Comment by jornbr** [comment]
As this is about a specific biogeochemical model (iow/spm) rather than FABM itself, it would be best answered by that model's maintainers. @knutaros, any comments?

**Comment by RuoLinCunJi** [comment]
@jornbr 
Hi Jorn!I m a new fabm user.I left you a message on Researchgate, I would like to ask you if there is a way to treat the plankton in the npzd model as a particle, I have tried applying fabm_particle but in the .nc file (output result) there is no difference with not applying fabm_particle. I am using the getm model.
Cheers!
