### ISSUE TITLE
Possible short berifing about FABM history and current status

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [fabm-model/fabm#23]
Hi @jornbr and @bolding 

I hope you are doing well. As a part of our effort to move toward coupling modular components and taking FABM as a good and successful example, I was wondering if you would be able to provide a briefing to our team (~15~20 minutes) at our next governance meeting. We are an international set of scientists/developers from agencies/academia. Please see more information here: https://github.com/oceanmodeling .

Our next meeting will be:

Ocean Modeling Collaboration Bi-monthly Meeting
Thursday, October 6 · 09:00 – 10:30 EDT
Google Meet joining info
Video call link: https://meet.google.com/eyy-zqbd-ppr
Or dial: ‪(US) +1 208-715-5331‬ PIN: ‪260 201 088‬#
More phone numbers: https://tel.meet/eyy-zqbd-ppr?pin=9418066551126
 
Let us know what you think.

Thanks,
@saeed-moghimi-noaa  and @brey

**Comment by bolding** [comment]
Hi @saeed-moghimi-noaa and @brey

Yes we will be interested in presenting the ideas behind FABM to you.

Jorn is on vacation right now when he returns we will take up the conversation on the form and content.

Best regards,
Karsten

**Comment by fenjuan** [comment]
I would be interested too 

Best
Fen

Sendt fra min iPhone

**Comment by saeed-moghimi-noaa** [comment]
All, 

This is an open forum, please feel free to call in using provided Google meet link. The date/time is for EDT. I can send invite to interested folks if you provide me with your emails.

Best,
-Saeed

**Comment by saeed-moghimi-noaa** [comment]
@bolding 

Thanks for your response.

Looking forward to hearing from you,

-Saeed

**Comment by fenjuan** [comment]
Thanks Saeed! 
***@***.***
Fenjuan Rose Schmidt Hu

Looking forward to the details of forum. :D
Have a nice weekend
Best
Fen

Sendt fra min iPhone

**Comment by jornbr** [comment]
Hi Saeed,

Thanks for the invitation; I'd be happy to present FABM at this meeting. Typically this will cover design principles, applications, community uptake. If there are specific topics you'd like to us to emphasize or add, do let me know.

Best,

Jorn

**Comment by saeed-moghimi-noaa** [comment]
Hi Jorn

It would be nice to meet you after a while. 

This would be a great plan. We would also like to hear about your experience for making FABM a successful model for being a module serving multiple modeling applications and frameworks.  We like to learn how we may model this for another physical processes e.g. infra-gravity waves module.

Thanks,
-Saeed

**Comment by jornbr** [comment]
Great, thanks. I'll keep this in mind while preparing.

Best,

Jorn

**Comment by saeed-moghimi-noaa** [comment]
@jornbr  @bolding  @fenjuan 
Just a reminder of the meeting next week. Your emails were stripped from the text by github. Please simply add this to your calendar. or send me an email to Saeed[dot]Moghimi[at]noaa[dot]gov. 

Let see if my email will make it to you :-)

Best,
@saeed-moghimi-noaa

Ocean Modeling Collaboration Bi-monthly Meeting
Thursday, October 6 · 09:00 – 10:30 EDT
Google Meet joining info
Video call link: https://meet.google.com/eyy-zqbd-ppr
Or dial: ‪(US) +1 208-715-5331‬ PIN: ‪260 201 088‬#
More phone numbers: https://tel.meet/eyy-zqbd-ppr?pin=9418066551126

**Comment by saeed-moghimi-noaa** [comment]
Here is the message I sent to the team:

All,

This is a friendly reminder of our meeting next week. FABM (https://github.com/fabm-model/fabm) model lead developers will brief us on their history and community building around how a specific module could support / operate with multiple ocean model.

This also relates to process coupling (e.g. IG waves, turbulence or sediment modules) v.s. domain coupling (Sea ice, surface waves or ocean).

Best,
-Saeed
