### ISSUE TITLE
fabm_particle

### ISSUE THREAD

**Issue by jornbr** [fabm-model/fabm#25]
@jornbr 
Hi Jorn!I m a new fabm user.I left you a message on Researchgate, I would like to ask you if there is a way to treat the plankton in the npzd model as a particle, I have tried applying fabm_particle but in the .nc file (output result) there is no difference with not applying fabm_particle. I am using the getm model.
Cheers!

_Originally posted by @RuoLinCunJi in https://github.com/fabm-model/fabm/issues/22#issuecomment-1226013852_

**Comment by RuoLinCunJi** [comment]
Dear Jorn
Thank you very much for your patient answer, I would like to ask you, is there some way to achieve particle tracking of phytoplankton?
Cheers
R.Lin

**Comment by jornbr** [comment]
That's equivalent to the Lagrangian/Individual Based Model approach described above. It would require:

* support in the hydrodynamic model (e.g., GETM) to maintain and track particles, or alternatively, an offline particle tracking tool that reads in currents/diffusivities from file
*   and a mechanism to ascribe behavior (growth, death, etc.) to those particles. For that part, FABM could be used.

However, I am not aware of any hydrodynamic model or offline particle tracing tool that allows FABM to be used to prescribe particle behavior, other than the experimental GOTM branch I referred to above. So the short answer is, no, not to my knowledge.

Best,

Jorn

**Comment by RuoLinCunJi** [comment]
Dear Jorn
Thank you for your guidance, and again for your detailed and patient answers！
Best wishes
R.Lin
