### ISSUE TITLE
pyfabm linking problem on ubuntu

### ISSUE THREAD

**Issue by platipodium** [fabm-model/fabm#26]
When using pyfabm, I get a runtime link error.

Installing and compiling on ubuntu 2022/04 with gfortran GNU Fortran (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 and python 3.9.7

```
$> cmake -B $(CWD)/build-python $(FABMDIR)/src/drivers/python
$> make -C $(CWD)/build-python -j4
$> make -C $(CWD)/build-python install
```

Then running (any) fabm application, .e.g.  `fabm_describe_model`, I get

```
Traceback (most recent call last):
  File "~/.local/bin/fabm_describe_model", line 5, in <module>
    from pyfabm.utils.fabm_describe_model import main
  File "~/.local/lib/python3.9/site-packages/pyfabm/__init__.py", line 49, in <module>
    fabm = ctypes.CDLL(str(dllpath))
  File "/opt/miniforge/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ~/.local/lib/python3.9/site-packages/pyfabm/libfabm_c.so: undefined symbol: signa_
```

**Comment by jornbr** [comment]
I've just added a branch to specifically test with ubuntu 22.04 in combination with gfortran 11 on GitHub Actions (https://github.com/fabm-model/fabm/actions/runs/3243546942/jobs/5318417720). That test seems to have succeeded. This environment is not 100% identical to yours (e.g., it uses gfortran 11.2 where you have 11.3), but it is quite close.  Moreover, the Python version should not matter as pyfabm is built as dynamic library.  I am not sure what could cause the difference... Are you still experiencing this problem?

**Comment by platipodium** [comment]
I tested the deviation from official fabm in our schism fork  https://github.com/schism-dev/fabm and narrowed the error down to the FABM implementation of the COSINE model.

**Comment by platipodium** [comment]
Their implementation pulls in a function that give the sign of the area ("signa") from a schism library which is of course not linked with other hosts.

**Comment by jornbr** [comment]
Thanks; that's good to know. Maybe worth mentioning that if there is a need to pass custom fields from SCHISM to COSINE or other BGC models, the best mechanism would be to define new standard variables for that purpose. As long as both host and BGC model do this and define the standard variables in the same way (in particular: same name and units), the data will be passed, without needing direct hooks into the host. But I am not sure whether that approach would make sense for "signa" or derived variables as I'm not sure what COSINE tries to do.
