### ISSUE TITLE
Allowing different DEFAULT_PREFIX (install directory)

### ISSUE THREAD

**Issue by jenniferagraham** [fabm-model/fabm#27]
Would it be possible to allow for a specified install directory, to avoid always using the default $HOME/local/fabm? 
e.g., modifying src/CMakeLists.txt to check for a defined FABM_HOME? 

```
... ~/GitHub/fabm]$ git diff src/CMakeLists.txt
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 0a0a720..338466f 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -160,7 +160,11 @@ if(WIN32)
     set(DEFAULT_PREFIX "$ENV{APPDATA}/fabm/${FABM_HOST}")
   endif()
 else()
-  set(DEFAULT_PREFIX "$ENV{HOME}/local/fabm/${FABM_HOST}")
+  if(DEFINED ENV{FABM_HOME})
+    set(DEFAULT_PREFIX "$ENV{FABM_HOME}")
+  else()
+    set(DEFAULT_PREFIX "$ENV{HOME}/local/fabm/${FABM_HOST}")
+  endif()
 endif()

```

**Comment by jornbr** [comment]
Yes, that is possible, but not very well documented. You can provide `-DCMAKE_INSTALL_PREFIX=<DIR>` in the call to cmake. In that case `<DIR>` replaces the default `$HOME/local/fabm/<HOST>`.

**Comment by jenniferagraham** [comment]
Thank you for the prompt response and that suggestion.
