### ISSUE TITLE
FABM's 0D driver broken installation

### ISSUE THREAD

**Issue by wathen** [fabm-model/fabm#46]
Noticed in [ERSEM automated testing](https://github.com/pmlmodelling/ersem/pull/117) the 0D driver installation is broken, I have checked locally and get the same error 
![image](https://github.com/fabm-model/fabm/assets/15614849/49efab51-2e5f-41f8-828f-254d2da57b11)

**Comment by jornbr** [comment]
That's likely because you are building the 0d driver with the developers' version of the GOTM code. It requires the latest stable GOTM version, currently v6.

**Comment by wathen** [comment]
Ahh ok, thanks for that! Maybe this could be added to the [wiki](https://github.com/fabm-model/fabm/wiki/0D-driver)

**Comment by jornbr** [comment]
Fully agree (and thanks for reminding me that that page existed!)

**Comment by jornbr** [comment]
The wiki has now been updated accordingly.
