### ISSUE TITLE
Typo in Wiki Text in "Developing a new biogeochemical model"

### ISSUE THREAD

**Issue by neumannd** [fabm-model/fabm#5]
In the paragraph describing the subroutine `_SET_SURFACE_EXCHANGE_(VARIABLEID,RATE)` there is the sentence

> `RATE` is the flux across the *bottom* interface in state variable units [...]

Probably it should read

> `RATE` is the flux across the *surface* interface in state variable units [...]

**Comment by jornbr** [comment]
thanks for this; it has now been corrected
