### ISSUE TITLE
Typo in the Wiki

### ISSUE THREAD

**Issue by fricour** [fabm-model/fabm#52]
Hi,

It's just a tiny little thing but in the Wiki, part _Developing a new biogeochemical model_, section _Making the model available_, you write the following 

_To make FABM aware of your new model, two lines must be added to your library, `src/models/INSTITUTE/model_library.F90`:_

while I think the fortran file should be `src/models/INSTITUTE/INSTITUTE_model_library.F90`.

Nothing much really but I found it confusing at first because I was looking for such a file in examples before realizing it was not needed.

**Comment by jornbr** [comment]
Fixed - thanks!
