### ISSUE TITLE
Problem about FABM

### ISSUE THREAD

**Issue by chevyyang** [fabm-model/fabm#85]
Hi, 
    My research is applying the model to simulate the nutrients distribution in semi-closed Bay and then analyze the trend of the change based on the model results. I want to add a wet atmospheric deposition to the model. 
  But I don’t know how to add these nutrient parameters in the wet atmospheric deposition file. I tried add the nutrients parameters directly in PRECIPITATION_FILE (i.e. adding ‘N1_p’,’N3_n’), however, the model did not read those parameters. I can not find the related setting part in the ‘nml’ file. I don’t know how add it in fabm.yaml. The nutrient parameters in the wet atmospheric deposition file should vary with time and location. I read the handbook and still can not find the procedure for how to add nutrient parameters in a wet atmospheric deposition file or how to add wet atmospheric deposition of nutrients. Is there any related tutorial? Or, Who should I try to consult?
Thank you all so much for your help in advance.
Best wishes! Have a nice day!

Chao

**Comment by bolding** [comment]
Hi

You need to provide a bit more information - e.g. what model are you using? 

Karsten

**Comment by chevyyang** [comment]
> Hi
> 
> You need to provide a bit more information - e.g. what model are you using?
> 
> Karsten

Thank you so much for your reply. I forgot to mention it. I used FVCOM-FABM-ERSEM

**Comment by bolding** [comment]
The handling of input/output is handled by the physical driver model - in this case FVCOM - and not by FABM. 

I have no experience with FVCOM but you'll have to ask some that has.

Karsten

**Comment by jornbr** [comment]
closing this as it is an FVCOM issue

Note that it is possible to set up surface fluxes to any state variable within `fabm.yaml`, and it is possible to specify constant values for these fluxes (and any other forcing) there too: https://github.com/fabm-model/fabm/discussions/43. However, space and/or time dependent forcing can only be provided via the physical model, FVCOM in this case.
