### ISSUE TITLE
Hello everyone,

### ISSUE THREAD

**Issue by Mehrnoosh-Abbasian** [fabm-model/fabm#88]
Hello everyone,

I am currently running GOTM-FABM and using the NIVA OxyDep model. In the nivaoxydep.f90 file, it seems that the model might depend on wind speed as a time series, but I'm not entirely sure. Could anyone help confirm if wind speed is indeed used as a time series in this model? Want to know that the wind speed is  read  in timeseries format as input in the model.
Mehrnoosh

_Originally posted by @Mehrnoosh-Abbasian in https://github.com/fabm-model/fabm/discussions/86_

**Comment by jornbr** [comment]
Please continue this discussion [here](https://github.com/fabm-model/fabm/discussions/86) if more information is required.
