### ISSUE TITLE
Compile error FABM-V1.0.0

### ISSUE THREAD

**Issue by qinwangxing** [fabm-model/fabm#9]
I encountered a compilation error, the previous version of FABM could be successfully complie, but the V1.0.0  encountered the following error:
ERSEM-master/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine c       all.   [REGISTER_STATE_DEPENDENCY]
call self%**register_state_dependency**(self%id_layer,'layer','m','depth of bottom interface of final layer', &
Does anybody know how to solve it?

**Comment by jornbr** [comment]
Hello,

This is a known issue with the latest stable release of ERSEM (19.04) in combination with FABM v1. It has been fixed in the developers' version of ERSEM, which will soon be released publicly. When ready, this release will be announced on the ERSEM mailing list.

Best,

Jorn

**Comment by xieyihui** [comment]
> 
> 
> I encountered a compilation error, the previous version of FABM could be successfully complie, but the V1.0.0 encountered the following error:
> ERSEM-master/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine c all. [REGISTER_STATE_DEPENDENCY]
> call self%**register_state_dependency**(self%id_layer,'layer','m','depth of bottom interface of final layer', &
> Does anybody know how to solve it?

Can you give me the qq number? I also encountered this problem

**Comment by qinwangxing** [comment]
> > I encountered a compilation error, the previous version of FABM could be successfully complie, but the V1.0.0 encountered the following error:
> > ERSEM-master/src/benthic_column_dissolved_matter.F90(96): error #8486: There is no matching specific subroutine for this type bound generic subroutine c all. [REGISTER_STATE_DEPENDENCY]
> > call self%**register_state_dependency**(self%id_layer,'layer','m','depth of bottom interface of final layer', &
> > Does anybody know how to solve it?
> 
> Can you give me the qq number? I also encountered this problem

That's OK, My e-mail is qinwangxing@gmail.com.

**Comment by jornbr** [comment]
This is fixed in the latest ERSEM release, 20.09.

Jorn

**Comment by bwang63** [comment]
Do you resolve it? I have the similar issue as:
error #8486: There is no matching specific subroutine for this type bound generic subroutine call.   [REGISTER_DIAGNOSTIC_VARIABLE]
